"""predict: {base model + every checkpoint} x eval split -> predictions.

The base model is always included as `checkpoint: null`. Base-vs-fine-tuned on
identical prompts with identical decoding is exactly the evidence the fine-tune
has to justify itself with, so it is generated by default rather than as an
afterthought.

Kept separate from `evaluate` because generation is the slow, GPU-bound part and
grader definitions change often — re-grade stored predictions instead.
"""

from __future__ import annotations

import json
import time

from ftpipe import config
from ftpipe.artifacts import Run
from ftpipe.backends import get_backend
from ftpipe.schema import read_jsonl


def run(cfg: dict, run: Run) -> dict:
    train_cfg = dict(cfg.get("train", {}) or {})
    predict_cfg = cfg.get("predict", {}) or {}
    split = predict_cfg.get("split", "val")

    rendered = run.read_manifest("render")["outputs"][split]["path"]
    canonical = read_jsonl(run.read_manifest("curate")["outputs"][split]["path"])
    by_id = {rec.id: rec for rec in canonical}

    prompts = []
    with open(rendered) as fh:
        for line in fh:
            if not line.strip():
                continue
            item = json.loads(line)
            # strip the gold assistant turn — this is inference
            item["messages"] = [m for m in item["messages"] if m["role"] != "assistant"]
            prompts.append(item)

    limit = predict_cfg.get("limit")
    if limit:
        prompts = prompts[: int(limit)]

    targets = [{"checkpoint": None, "step": 0, "label": "base"}]
    if predict_cfg.get("include_checkpoints", True):
        for ckpt in run.read_manifest("train")["outputs"]["checkpoints"]:
            targets.append({"checkpoint": ckpt["checkpoint"], "step": ckpt["step"],
                            "label": f"step-{ckpt['step']}"})

    backend = get_backend(train_cfg)
    out_dir = run.stage_dir("predict")
    outputs = []

    for target in targets:
        started = time.time()
        texts = backend.generate(
            target["checkpoint"], prompts,
            max_new_tokens=int(predict_cfg.get("max_new_tokens", 128)),
            temperature=float(predict_cfg.get("temperature", 0.0)),
            batch_size=int(predict_cfg.get("batch_size", 8)),
        )
        elapsed = time.time() - started

        path = out_dir / f"{target['label']}.jsonl"
        with open(path, "w") as fh:
            for item, text in zip(prompts, texts):
                fh.write(json.dumps({
                    "id": item["id"], "task": item.get("task"),
                    "prediction": text,
                    "target": by_id[item["id"]].target if item["id"] in by_id else None,
                }, ensure_ascii=False) + "\n")

        outputs.append({**target, "path": str(path), "n": len(prompts),
                        "seconds": round(elapsed, 2),
                        "seconds_per_item": round(elapsed / max(1, len(prompts)), 3)})
        print(f"  · {target['label']}: {len(prompts)} predictions in {elapsed:.1f}s")

    run.write_manifest(
        "predict",
        inputs={"split": split, "rendered": rendered, "decoding": predict_cfg},
        outputs={"predictions": outputs},
    )
    return {"split": split, "n_prompts": len(prompts),
            "variants": [o["label"] for o in outputs]}
